default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "recipes_user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "recipes_password" } %>

development:
  <<: *default
  database: recipes_development

test:
  <<: *default
  database: recipes_test
  username: recipes_user
  password: recipes_password
  host: db

production:
  <<: *default
  database: recipes_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

